---
- name: configure / Set global configuration file
  template:
    src: nginx.conf.j2
    dest: "{{ nginx_vhost_conf }}"
    owner: root
    group: root
    mode:  0644

- name: configure / Strat nginx service
  systemd:
    name: nginx
    state: reloaded
    enabled: yes

- name: configure / Wait for nginx restart
  wait_for:
    host: "{{ ansible_eth1.ipv4.address }}"
    port:  "{{ nginx_service_port }}"
    delay: 3
    timeout: 60

- name: configure / sample file output
  copy:
    src: index.php
    dest: "{{ nginx_document_root }}/index.php"
