---
- name: upgrade pip
  pip:
    name: pip
    executable: pip3
    state: latest

- name: install / Install required packages
  package:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items: "{{ nginx_packages }}"
