---
# - include: install.yml   tags=nginx
# - include: configure.yml tags=nginx

- name: install required packages
  package:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items: "{{ imagick_packages }}"

- name: clone imagick.git
  git:
    repo: "{{ imagick_repository }}"
    dest: "{{ imagick_download_dir }}"
    depth: 1

- name: phpize
  shell: phpize
  args:
    chdir: "{{ imagick_download_dir }}"

- name: configure
  become: yes
  shell: "./configure" #--with-php-config={{ imagick_phpize_path }}"
  args:
    chdir: "{{ imagick_download_dir }}"
  ignore_errors: yes

- name: make
  make:
    chdir: "{{ imagick_download_dir }}"

- name: make install
  make:
    target: install
    chdir: "{{ imagick_download_dir }}"

- name: add imagick.so to php.ini
  lineinfile:
    dest: "{{ imagick_php_ini_path }}"
    line: "\t\textension = {{ imagick_php_extension_dir }}/imagick.so"

# pecl channel-update pecl.php.net
