---
#register the path for php.ini
- name: register the path of php.ini
  shell: 'php --ini | sed -n 2p | sed -e "s/^Loaded.*\ //g"'
  register: path_php_ini
  changed_when: no

#register the path for extension_dir
- name: register the value of extension_dir
  shell: 'php -i | grep extension_dir | sed -e "s/^extension_dir\ =>[^=]*=>\ //g" | sed -n 1p'
  register: extension_dir
  changed_when: no

- name: install required packages
  package:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items: "{{ imagick_packages }}"

- name: clone imagick.git
  git:
    repo: "{{ imagick_repository }}"
    dest: "{{ imagick_download_dir }}"
    depth: 1

- name: phpize
  shell: phpize
  args:
    chdir: "{{ imagick_download_dir }}"

- name: configure
  become: yes
  shell: "./configure"
  args:
    chdir: "{{ imagick_download_dir }}"

- name: make
  make:
    chdir: "{{ imagick_download_dir }}"

- name: make install
  make:
    target: install
    chdir: "{{ imagick_download_dir }}"

- name: add imagick.so to php.ini
  lineinfile:
    dest: "{{ path_php_ini.stdout }}"
    line: "extension = {{ extension_dir.stdout }}/imagick.so"
