---
# - include: install.yml   tags=nginx
# - include: configure.yml tags=nginx

- name: install required packages
  package:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items: "{{ imagick_packages }}"

- name: clone imagick.git
  git:
    repo: "{{ imagick_repository }}"
    dest: "{{ imagick_download_dir }}"
    depth: 1

- name: phpize
  shell: "{{ imagick_phpize_path}}"

- name: configure
  shell: "./configure --with-php-config={{ imagick_phpize_path }}"
  args:
    chdir: "{{ imagick_download_dir }}"

- name: make install
  shell: make install
  args:
    chdir: "{{ imagick_download_dir }}"

- name: add imgick.so to php.ini
  lineinfile:
    dest: "{{ imgick_php_ini_path }}"
    line: "\t\textension = {{ imagick_php_extension_dir }}/imgick.so"
